### ISSUE TITLE
Support prerelease tags

### ISSUE THREAD

**Issue by tcrawford-figure** [FigureTechnologies/gradle-semver-plugin#56]
Support "RC" or "prerelease" suffix to denote that something is a prerelease.

**Comment by jeffypooo** [comment]
@tcrawford-figure you could use the version prefix for that i think?

**Comment by tcrawford-figure** [comment]
@jeffypooo We _could_. I think it would end up being like rc-1.2.5. I envisioned this being suffixed like how [detekt - example v1.22.0-RC3](https://github.com/detekt/detekt/releases/tag/v1.22.0-RC3) does their RCs (though I know their manually created, it'd be nice to have these generated)

**Comment by tcrawford-figure** [comment]
@jeffypooo prerelease tags are supported in v2 (which should hopefully be available in the coming days pending Gradle plugin portal approval)
